networks:
  default:
    external:
      name: vd
services:
  metabase:
    optional: metabase is Web tools for BI with dashboard
    expose: 3000
    image: metabase/metabase
    network_mode: "bridge"
    environment:
    - MB_DB_FILE=/file/metabase.db
    links:
    - db
    volumes:
    - .:/file
  pgadmin:
    optional: Pgadmin v4 is postgresql Web GUI
    expose: 5050
    image: fenglc/pgadmin4
    links:
      - db
  db:
    image: akretion/voodoo-postgresql
    environment:
    - POSTGRES_USER=odoo
    - POSTGRES_DB=db
    volumes:
    - .db/data/:/var/lib/postgresql/data
    - .db/socket/:/var/run/postgresql/
  mailcatcher:
    optional: Mailcatcher is a fake mail server
    expose: 1080
    image: akretion/lightweight-mailcatcher
  odoo:
    image: akretion/voodoo:latest
    expose: 8069
    environment:
    - PYTHONDONTWRITEBYTECODE=True
    links:
    - db
    volumes:
    - .:/workspace
    - .db/socket/:/var/run/postgresql/
version: '2'
